### ISSUE TITLE
Grammaticale fout

### ISSUE THREAD

**Issue by gerritdevriese** [Bart-Roels/ProjectMertens#1]
Overuuren is maar met één u :)

**Comment by Bart-Roels** [comment]
HAHAHAHHAHAHA WHUTTT? wa die gij hier ineens?!

**Comment by Bart-Roels** [comment]
Fixed!

Van: gerritdevriese <notifications@github.com>
Verzonden: woensdag 21 oktober 2020 17:10
Aan: Bart-Roels/ProjectMertens <ProjectMertens@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [Bart-Roels/ProjectMertens] Grammaticale fout (#1)


Overuuren is maar met één u :)
